name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/usernamecompanyname/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Generate a NuGet package
      run: dotnet pack --no-build -c Release -o .
    - name: Push to GitHub package registry
      run: dotnet nuget push *.nupkg
