name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with: 
        dotnet-version: 3.1.101
        servers: '[{"id": "github", "username": "x-access-token", "password": "${GITHUB_TOKEN}"}]'
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release --version-suffix action-testing -o "./packages"
    - name: Publish
      run: |
        for f in ./packages/*.nupkg
        do
          curl -vX PUT -u "username:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/github-actions-awesomeness/
        done
      if: github.event_name == 'push'
